<table class="table-bordered table-bus-seats mt-2">
    <tr>
        <td class="bg-primary text-light"><span>D1W</span></td>
        <td><span>D2W</span></td>
        <td><span>-</span></td>
        <td><span>C2W</span></td>
        <td><span>C1W</span></td>
    </tr>
    <tr>
        <td><span>D3W</span></td>
        <td><span>D4A</span></td>
        <td><span>-</span></td>
        <td><span>C4A</span></td>
        <td><span>C3W</span></td>
    </tr>
    <tr>
        <td><span>D5W</span></td>
        <td><span>D6A</span></td>
        <td><span>-</span></td>
        <td><span>C6A</span></td>
        <td><span>C5W</span></td>
    </tr>
    <tr>
        <td><span>D7W</span></td>
        <td><span>D8A</span></td>
        <td><span>-</span></td>
        <td><span>C8A</span></td>
        <td><span>C7W</span></td>
    </tr>
    <tr>
        <td><span>D9W</span></td>
        <td><span>D10A</span></td>
        <td><span>-</span></td>
        <td><span>C10A</span></td>
        <td><span>C9W</span></td>
    </tr>
    <tr>
        <td><span>D11W</span></td>
        <td><span>D12A</span></td>
        <td><span>-</span></td>
        <td><span>C12A</span></td>
        <td><span>C11W</span></td>
    </tr>
    <tr>
        <td><span>D13W</span></td>
        <td><span>D14A</span></td>
        <td><span>-</span></td>
        <td><span>C14A</span></td>
        <td><span>C13W</span></td>
    </tr>
    <tr>
        <td><span>D15W</span></td>
        <td><span>D16A</span></td>
        <td><span>-</span></td>
        <td><span>C16A</span></td>
        <td><span>C15W</span></td>
    </tr>
    <tr>
        <td><span>D17W</span></td>
        <td><span>D18A</span></td>
        <td><span>-</span></td>
        <td><span>C18A</span></td>
        <td><span>C17W</span></td>
    </tr>
    <tr>
        <td><span>D19W</span></td>
        <td><span>D20A</span></td>
        <td><span>B21C</span></td>
        <td><span>C20A</span></td>
        <td><span>C19W</span></td>
    </tr>
</table>